# fly.toml app configuration file generated for devpad on 2025-01-27T01:51:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devpad'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
