/**
 * Integration test: render every template with three representative
 * flag combos, compare the rendered tree against a committed golden
 * directory, and finally `tsc --noEmit` the generated package to assert
 * it typechecks.
 *
 * Goldens live under `packages/cli/tests/golden/<combo>/`. They're
 * regenerated by running `UPDATE_GOLDENS=1 bun test scaffold-init-golden`.
 */

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { beforeEach, describe, expect, test } from "bun:test";
import { type BuildShape, type DefaultGateKind, type RolloutMode, scaffold_package } from "../../src/scaffolder/index";

const GOLDEN_ROOT = path.resolve(import.meta.dir, "..", "golden");
const FIXED_NOW = new Date(Date.UTC(2026, 4, 17));
const UPDATE_GOLDENS = process.env.UPDATE_GOLDENS === "1";

type Combo = {
	dir_name: string;
	package_name: string;
	rollout: RolloutMode;
	default_gate: DefaultGateKind;
	build_shape: BuildShape;
};

const COMBOS: Combo[] = [
	{
		dir_name: "anthropic-search",
		package_name: "anthropic-search",
		rollout: "atomic",
		default_gate: "auto",
		build_shape: "single-file",
	},
	{
		dir_name: "gradual-manual",
		package_name: "gradual-manual",
		rollout: "gradual",
		default_gate: "manual",
		build_shape: "single-file",
	},
	{
		dir_name: "gradual-analysis",
		package_name: "gradual-analysis",
		rollout: "gradual",
		default_gate: "analysis",
		build_shape: "single-file",
	},
	{
		dir_name: "directory-bundle",
		package_name: "directory-bundle",
		rollout: "gradual",
		default_gate: "auto",
		build_shape: "directory-bundle",
	},
];

const list_files = async (root: string): Promise<string[]> => {
	const out: string[] = [];
	const walk = async (dir: string): Promise<void> => {
		const entries = await readdir(dir, { withFileTypes: true });
		for (const entry of entries) {
			const full = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				await walk(full);
				continue;
			}
			out.push(path.relative(root, full));
		}
	};
	await walk(root);
	return out.toSorted();
};

const copy_tree = async (src: string, dest: string): Promise<void> => {
	await rm(dest, { recursive: true, force: true });
	await mkdir(dest, { recursive: true });
	const files = await list_files(src);
	for (const rel of files) {
		const src_full = path.join(src, rel);
		const dest_full = path.join(dest, rel);
		await mkdir(path.dirname(dest_full), { recursive: true });
		await writeFile(dest_full, await readFile(src_full));
	}
};

const make_tmp_target = async (): Promise<string> => {
	const tmp = await mkdtemp(path.join(tmpdir(), "devpad-scaffold-"));
	// scaffold_package refuses to overwrite — point at a child that does
	// NOT yet exist so the orchestrator owns directory creation.
	return path.join(tmp, "out");
};

beforeEach(() => {
	// No-op; per-test temp dirs are created inline.
});

describe("scaffold_package — golden tree", () => {
	for (const combo of COMBOS) {
		test(`${combo.dir_name} matches committed golden`, async () => {
			const target = await make_tmp_target();
			const result = await scaffold_package(
				{
					package_name: combo.package_name,
					target_dir: target,
					rollout: combo.rollout,
					default_gate: combo.default_gate,
					build_shape: combo.build_shape,
					skip_install: true,
					skip_git: true,
				},
				{ now: FIXED_NOW },
			);
			expect(result.ok).toBe(true);
			if (!result.ok) throw new Error(`scaffold failed: ${result.error.message}`);

			const golden_dir = path.join(GOLDEN_ROOT, combo.dir_name);
			if (UPDATE_GOLDENS) {
				await copy_tree(target, golden_dir);
				console.log(`updated golden: ${golden_dir}`);
				await rm(path.dirname(target), { recursive: true, force: true });
				return;
			}

			expect(existsSync(golden_dir)).toBe(true);

			const actual_files = await list_files(target);
			const expected_files = await list_files(golden_dir);
			expect(actual_files).toEqual(expected_files);

			for (const rel of actual_files) {
				const actual = await readFile(path.join(target, rel), "utf8");
				const expected = await readFile(path.join(golden_dir, rel), "utf8");
				if (actual !== expected) {
					throw new Error(`golden drift in ${rel}\n--- expected\n${expected}\n+++ actual\n${actual}`);
				}
			}

			await rm(path.dirname(target), { recursive: true, force: true });
		});
	}
});

describe("scaffold_package — typecheck", () => {
	// `bunx tsc` startup + downloading typescript on cold cache can push past
	// the default 5s test timeout; give it room.
	test("generated atomic+auto package typechecks", async () => {
		const target = await make_tmp_target();
		const result = await scaffold_package(
			{
				package_name: "tc-fixture",
				target_dir: target,
				rollout: "atomic",
				default_gate: "auto",
				build_shape: "single-file",
				skip_install: true,
				skip_git: true,
			},
			{ now: FIXED_NOW },
		);
		expect(result.ok).toBe(true);
		if (!result.ok) throw new Error(`scaffold failed: ${result.error.message}`);

		// Drop a tsconfig that points at the workspace's installed
		// types — generated package has no node_modules, so we can't run
		// its own tsconfig as-is. The relaxed config below verifies that
		// the *generated TypeScript source* parses + type-checks.
		const tsconfig = {
			compilerOptions: {
				target: "ES2022",
				module: "ESNext",
				moduleResolution: "bundler",
				strict: true,
				skipLibCheck: true,
				noEmit: true,
				allowImportingTsExtensions: true,
				isolatedModules: true,
				types: [],
				// Stub out the imports the scaffold makes — generated
				// package source references types it doesn't ship with.
				paths: {
					"cloudflare:workers": ["./types-stub.d.ts"],
					"@devpad/pipeline-templates": ["./types-stub.d.ts"],
					"@cloudflare/workers-types": ["./types-stub.d.ts"],
					"@f0rbit/corpus": ["./types-stub.d.ts"],
					"@playwright/test": ["./types-stub.d.ts"],
					alchemy: ["./types-stub.d.ts"],
					"alchemy/cloudflare": ["./types-stub.d.ts"],
				},
			},
			include: ["src/**/*.ts", "infra.ts", "pipeline.ts", "grants.ts", "e2e/**/*.ts", "types-stub.d.ts"],
		};
		await writeFile(path.join(target, "tsconfig.json"), JSON.stringify(tsconfig, null, "\t"));

		// Minimal ambient declarations covering everything the scaffold imports.
		const stub = [
			"declare module 'cloudflare:workers' { export class WorkerEntrypoint<E = unknown> { env: E; fetch?(request: Request): Promise<Response>; } }",
			"declare global { type Service<_T = unknown> = { fetch: typeof fetch }; type Fetcher = { fetch: typeof fetch }; const process: { env: Record<string, string | undefined>; }; }",
			"declare module '@devpad/pipeline-templates' { export const manual: () => unknown; export const auto: (opts?: { afterBake?: boolean }) => unknown; export const analysis: (ref: { template_id: string }) => unknown; export const extendTemplate: (overrides: any) => { ok: boolean }; }",
			"declare module '@cloudflare/workers-types' { export type SecretsStoreSecret = { get(): Promise<string> }; }",
			"declare module '@playwright/test' { type Req = { get(url: string): Promise<{ status(): number; json(): Promise<any> }> }; type Ctx = { request: Req }; export const test: (name: string, fn: (ctx: Ctx) => Promise<void>) => void; export const expect: (v: any) => { toBe: (v: any) => void; }; export const defineConfig: <T>(config: T) => T; }",
			"declare module 'alchemy' { type Alchemy = { stage: string; finalize(): Promise<void>; secret: { env: Record<string, string | undefined> } }; type AlchemyFn = ((name: string) => Promise<Alchemy>) & { secret: { env: Record<string, string | undefined> } }; const fn: AlchemyFn; export default fn; }",
			"declare module 'alchemy/cloudflare' { export type Bindings = Record<string, unknown>; export const Worker: (name: string, opts: any) => Promise<any>; export const WorkerRef: (opts: { service: string }) => any; export const Secret: (name: string, opts: any) => Promise<any>; export const SecretsStore: (name: string, opts: any) => Promise<any>; }",
			"declare module '@f0rbit/corpus' { export type Result<T, E> = { ok: true; value: T } | { ok: false; error: E }; export const format_error: (e: unknown) => string; export const try_catch_async: <T, E>(fn: () => Promise<T>, on_error: (e: unknown) => E) => Promise<Result<T, E>>; }",
			"export {};",
		].join("\n");
		await writeFile(path.join(target, "types-stub.d.ts"), stub);

		const proc = spawnSync("bunx", ["tsc", "-p", "tsconfig.json"], { cwd: target, encoding: "utf8" });
		if (proc.status !== 0) {
			throw new Error(`tsc failed:\n${proc.stdout}\n${proc.stderr}`);
		}

		await rm(path.dirname(target), { recursive: true, force: true });
	}, 60_000);
});

// Silence unused-import warning when stat is dead-stripped — keep it
// available for future tree-comparison improvements.
void stat;
