-- CreateEnum
CREATE TYPE "ACTION_TYPE" AS ENUM ('CREATE_TASK', 'UPDATE_TASK', 'DELETE_TASK', 'CREATE_PROJECT', 'UPDATE_PROJECT', 'DELETE_PROJECT', 'CREATE_TAG', 'UPDATE_TAG', 'DELETE_TAG', 'CREATE_MODULE', 'UPDATE_MODULE', 'DELETE_MODULE');

-- CreateTable
CREATE TABLE "Action" (
    "id" UUID NOT NULL,
    "owner_id" TEXT NOT NULL,
    "type" "ACTION_TYPE" NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "data" JSON NOT NULL DEFAULT '{}',

    CONSTRAINT "Action_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Action" ADD CONSTRAINT "Action_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
